# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'system-task' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for system-task
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'RealmSwift'
  pod 'Alamofire'

end
